[package]
name = "blis-experimental-sys"
version = "0.1.0"
authors = [
  "bluss",
]
license = "BSD-3-Clause"
description = "Experimental bindings for BLIS linear algebra package"
repository = "github.com/"

publish = false
build = "build.rs"

[features]
system = []
